print("Day 1 - Python Print Function\nThe function is declared like this:\nprint('what to print')")
print("Day 1 - String Manipulation")
print('String concatenation is done using the "+" sign')
print('E.g print ("Hello" + "World!")')
print("New lines can be created wih a backlash and n")