print("Welcome to the Tip Calculator.")
Total_bill = int(input("What was the total bill?\n"))
Number_of_people = int(input("How many people to split the bill?\n"))
Percentage = int(input("What percentage tip would you like to give? 10, 12 or 15?\n"))
Amount_per_person = str(((Total_bill * Percentage/100) + Total_bill)/Number_of_people)
print("Each person should pay: " + "$" + Amount_per_person)
