print("Welcome to the Tip Calculator.")
Total_bill = float(input("What was the total bill?\n$"))
Number_of_people = int(input("How many people to split the bill?\n"))
Percentage = int(input("What percentage tip would you like to give? 10, 12 or 15?\n"))
Amount_per_person = round(((Total_bill * Percentage/100) + Total_bill)/Number_of_people, 2)
print(f"Each person should pay: ${Amount_per_person}")
